// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tictactoe.API.Data;

#nullable disable

namespace Tictactoe.API.Migrations
{
    [DbContext(typeof(TictactoeContext))]
    partial class TictactoeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tictactoe.API.Models.PlayerInfo", b =>
                {
                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("PlayerInfo");
                });

            modelBuilder.Entity("Tictactoe.API.Models.Room", b =>
                {
                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("GameRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
